title: James mann
description: > # this means to ignore newlines until "baseurl:"
  Hi, this will be my personal website going forward. I'll try to keep it updated with things I'm doing, projects
  I'm working on and maybe even a blog post. If I ever get around to it.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://broverfitter.github.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: James Mann # add your name
author-img: james.jpg # add your photo
about-author: Hi there, I'm James, I'm an undergraduate studying computer science at UCL. I like to row and play chess and read.
social-twitter: broverfitter
social-facebook: 
social-github: broverfitter # add your Github handle
social-linkedin: jrhmann
social-email: james.mann.24@ucl.ac.uk
current_book: What's wrong with the world - G.K. Chesterton

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
